[package]
name = "broker"
version = "0.0.1"
edition = "2021"
description = "The bridge between FOSSA and internal DevOps services"
readme = "README.md"
homepage = "https://github.com/fossas/broker"
repository = "https://github.com/fossas/broker"
license = "Apache-2.0"
exclude = [ "docs", ".github" ]
publish = false # rather than publishing this to crates.io, we'll provide releases here on GitHub.

[dependencies]
clap = { version = "4.1.6", features = ["derive", "cargo", "env"] }
error-stack = { version = "0.3.1", features = ["spantrace", "hooks"] }
thiserror = "1.0.36"

[build-dependencies]
semver = "1"
error-stack = { version = "0.3", features = ["hooks"] }
thiserror = "1.0.36"

[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
