[package]
name = "broker"
version = "0.1.0-pre"
edition = "2021"
description = "The bridge between FOSSA and internal DevOps services"
readme = "README.md"
homepage = "https://github.com/fossas/broker"
repository = "https://github.com/fossas/broker"
license = "Apache-2.0"
exclude = [ "docs", ".github" ]
publish = false # rather than publishing this to crates.io, we'll provide releases here on GitHub.

[dependencies]
bytesize = { version = "1.2.0", features = ["serde"] }
clap = { version = "4.1.8", features = ["derive", "cargo", "env"] }
colored = "2.0.0"
derive-new = "0.5.9"
derive_more = "0.99.17"
dirs = "4.0.0"
error-stack = { version = "0.3.1", features = ["spantrace", "hooks"] }
getset = "0.1.2"
humantime = "2.1.0"
once_cell = "1.17.1"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
subtle = "2.5.0"
thiserror = "1.0.38"
tokio = { version = "1.26.0", features = ["full"] }
url = "2.3.1"
base64 = "0.21.0"

[dev-dependencies]
insta = { version = "1.28.0", features = ["filters", "json", "yaml"] }
proptest = "1.1.0"
strum = { version = "0.24.1", features = ["derive"] }
test-strategy = "0.3.0"

[build-dependencies]
error-stack = { version = "0.3.1", features = ["hooks"] }
thiserror = "1.0.38"

[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
