[package]
name = "broker"
version = "0.0.2"
edition = "2021"
description = "The bridge between FOSSA and internal DevOps services"
readme = "README.md"
homepage = "https://github.com/fossas/broker"
repository = "https://github.com/fossas/broker"
license = "Apache-2.0"
exclude = [ "docs", ".github" ]
publish = false # rather than publishing this to crates.io, we'll provide releases here on GitHub.

[dependencies]
clap = { version = "4.1.6", features = ["derive", "cargo", "env"] }
colored = "2.0.0"
derive_more = "0.99.17"
dirs = "4.0.0"
error-stack = { version = "0.3.1", features = ["spantrace", "hooks"] }
getset = "0.1.2"
thiserror = "1.0.38"
url = "2.3.1"

[build-dependencies]
error-stack = { version = "0.3", features = ["hooks"] }
thiserror = "1.0.38"

[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
