[advisories]
ignore = [
  # Valid, but low impact for this application. 
  # Upstream fix is already PR'd, awaiting maintainer action: https://github.com/Axcient/rolling-file-rs/pull/6
  "RUSTSEC-2020-0071"
]
