[advisories]
ignore = [
  # Valid, but low impact for this application. 
  # Upstream fix is already PR'd, awaiting maintainer action: https://github.com/Axcient/rolling-file-rs/pull/6
  "RUSTSEC-2020-0071"

  # Valid, but low impact for this application.
  # Fix blocked on upstream: https://github.com/launchbadge/sqlx/pull/2094
  # See module documentation in 'src/db/sqlite.rs' for more context.
  "CVE-2022-35737"
]
