name: Release Docker

# Runs this workflow when the following workflows "complete".
#
# Note that "complete" doesn't imply success:
# https://github.com/orgs/community/discussions/26238
# TL;DR: Gate jobs on `if: ${{ github.event.workflow_run.conclusion == 'success' }}`.
on:
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: 
      - completed

jobs:
  release-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - name: cargo-version
        run: echo "::set-output name=name::$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)"
        id: tag
      - uses: docker/metadata-action@v3
        id: meta
        with:
          labels: |
            org.opencontainers.image.title=FOSSA Broker
            org.opencontainers.image.description=The bridge between FOSSA and internal DevOps services
            org.opencontainers.image.url=https://github.com/fossas/broker
            org.opencontainers.image.source=https://github.com/fossas/broker
            org.opencontainers.image.vendor=FOSSA
          images: |
            ghcr.io/fossas/broker/broker
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag.outputs.name }}
            type=sha
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: fossas
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
