name: static analysis
on: pull_request

# Run checkers independently, so you see errors from each.
jobs:
  # Linting
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features -- -D warnings

  # Formatting
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - run: cargo fmt
    - run: git diff --exit-code

  # Ensure every crate can actually build
  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo build

  # Ensure dependencies are up to date.
  #
  # If you're getting this error in CI, it's just letting you know that there are dependency updates available;
  # ideally update them but feel free to leave them for later as well.
  updated-advisory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-upgrades,cargo-edit
    - run: cargo upgrade
    - run: git diff --exit-code
