name: test
on: push

jobs:
  all:
    name: test ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - run: cargo nextest run
    # nextest doesn't run doctests, but does test everything else: https://github.com/nextest-rs/nextest/issues/16
    # run doctests after; this won't result in any extra rebuilds and is very quick.
    # doctest overview: https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html
    - run: cargo test --doc
